import { TourStep } from '../../../contexts/TourContext';

export const adminTourSteps: TourStep[] = [
  {
    id: 'welcome',
    title: 'Welcome to Your Admin Dashboard! 🎉',
    content: 'Welcome to Dino! As an admin, you have comprehensive control over your venue operations. Let\'s take a quick tour to show you the key features that will help you manage your restaurant efficiently.',
    target: '[data-tour="dashboard-header"]',
    placement: 'bottom',
    nextButtonText: 'Let\'s Start!',
    showSkip: true,
  },
  {
    id: 'stats-overview',
    title: 'Today\'s Performance at a Glance 📊',
    content: 'These cards show your key metrics for today: total orders, revenue, table occupancy, and active menu items. This gives you an instant overview of how your venue is performing.',
    target: '[data-tour="stats-cards"]',
    placement: 'bottom',
    nextButtonText: 'Show Me More',
  },

  {
    id: 'order-status',
    title: 'Order Status Breakdown 🍽️',
    content: 'This pie chart shows the current status of all orders - pending, preparing, ready, and served. It helps you understand your kitchen\'s current workload at a glance.',
    target: '[data-tour="order-status-chart"]',
    placement: 'left',
    nextButtonText: 'Continue',
  },
  {
    id: 'table-status',
    title: 'Table Management Overview 🪑',
    content: 'Monitor your table occupancy with this visual breakdown. You can see which tables are occupied, available, or need attention. This helps optimize seating arrangements.',
    target: '[data-tour="table-status-chart"]',
    placement: 'right',
    nextButtonText: 'Show Orders',
  },
  {
    id: 'recent-orders',
    title: 'Recent Orders Management 📋',
    content: 'Here you can see the latest orders with their status, table numbers, and amounts. You can view details or edit orders directly from this table. This is your command center for order management.',
    target: '[data-tour="recent-orders"]',
    placement: 'top',
    nextButtonText: 'Quick Actions',
  },
  {
    id: 'quick-actions',
    title: 'Quick Access to Key Features ⚡',
    content: 'These buttons give you quick access to the most important admin functions: managing orders, menu items, tables, and staff. Use these for fast navigation to key areas.',
    target: '[data-tour="quick-actions"]',
    placement: 'top',
    nextButtonText: 'Navigation',
  },
  {
    id: 'navigation',
    title: 'Main Navigation Menu 🧭',
    content: 'Use the sidebar navigation to access all admin features. You can manage your menu, view detailed analytics, handle user permissions, and configure venue settings.',
    target: '[data-tour="sidebar-navigation"]',
    placement: 'right',
    nextButtonText: 'Orders Deep Dive',
  },
  {
    id: 'orders-management',
    title: 'Complete Order Management 📦',
    content: 'In the Orders section, you can view all orders, update their status, handle payments, and track delivery. You can filter by status, date, or table to find specific orders quickly.',
    target: '[data-tour="orders-nav"]',
    placement: 'right',
    nextButtonText: 'Menu Control',
  },
  {
    id: 'menu-management',
    title: 'Menu & Inventory Control 🍕',
    content: 'Manage your entire menu here - add new items, update prices, organize categories, and control availability. You can also upload images and set preparation times for each dish.',
    target: '[data-tour="menu-nav"]',
    placement: 'right',
    nextButtonText: 'Table Setup',
  },
  {
    id: 'table-management',
    title: 'Table & Seating Configuration 🏪',
    content: 'Set up your restaurant layout, manage table availability, and organize seating areas. You can create table areas, set capacities, and track occupancy in real-time.',
    target: '[data-tour="tables-nav"]',
    placement: 'right',
    nextButtonText: 'Staff Management',
  },
  {
    id: 'user-management',
    title: 'Staff & Permissions Management 👥',
    content: 'Add staff members, assign roles, and manage permissions. You can control who has access to different features and ensure your team has the right level of access.',
    target: '[data-tour="users-nav"]',
    placement: 'right',
    nextButtonText: 'Analytics',
  },

  {
    id: 'settings',
    title: 'Venue Settings & Configuration ⚙️',
    content: 'Configure your venue details, operating hours, payment methods, and other settings. You can also manage your subscription and update business information here.',
    target: '[data-tour="settings-nav"]',
    placement: 'right',
    nextButtonText: 'Complete Tour',
  },
  {
    id: 'completion',
    title: 'You\'re All Set! 🚀',
    content: 'Congratulations! You now know the key features of your admin dashboard. Remember, you can always restart this tour from your user profile settings. Start managing your venue like a pro!',
    target: '[data-tour="dashboard-header"]',
    placement: 'center',
    nextButtonText: 'Start Managing',
    showSkip: false,
  },
];

export default adminTourSteps;