import { TourStep } from '../../../contexts/TourContext';

export const operatorTourSteps: TourStep[] = [
  {
    id: 'welcome',
    title: 'Welcome to Your Operator Dashboard! 👋',
    content: 'Welcome to Dino! As an operator, you\'re the heart of daily operations. This dashboard is designed to help you manage orders efficiently and keep everything running smoothly. Let\'s explore the key features!',
    target: '[data-tour="dashboard-header"]',
    placement: 'bottom',
    nextButtonText: 'Show Me Around',
    showSkip: true,
  },
  {
    id: 'order-stats',
    title: 'Live Order Status Overview 📊',
    content: 'These colorful cards show you the current state of all orders: pending orders waiting for confirmation, orders being prepared in the kitchen, and orders ready to serve. The numbers update in real-time!',
    target: '[data-tour="order-stats"]',
    placement: 'bottom',
    nextButtonText: 'Active Orders',
  },
  {
    id: 'active-orders',
    title: 'Active Orders Management 🍽️',
    content: 'This is your main workspace! Here you can see all active orders with their details: table number, items, amount, current status, and estimated ready time. You can update order status with one click.',
    target: '[data-tour="active-orders-table"]',
    placement: 'top',
    nextButtonText: 'Order Actions',
  },
  {
    id: 'order-actions',
    title: 'Quick Order Status Updates ⚡',
    content: 'Use these action buttons to move orders through their lifecycle: Confirm pending orders, mark them as preparing when kitchen starts, set as ready when done, and finally mark as served when delivered to customers.',
    target: '[data-tour="order-action-buttons"]',
    placement: 'top',
    nextButtonText: 'Table Status',
  },
  {
    id: 'table-occupancy',
    title: 'Table Occupancy Tracking 🪑',
    content: 'Keep track of how many tables are currently occupied versus available. This helps you manage seating efficiently and know when you\'re approaching full capacity.',
    target: '[data-tour="table-occupancy"]',
    placement: 'left',
    nextButtonText: 'Refresh Data',
  },
  {
    id: 'refresh-controls',
    title: 'Real-time Data Updates 🔄',
    content: 'The dashboard automatically refreshes every 30 seconds, but you can manually refresh anytime using this button. Stay updated with the latest order status and table information.',
    target: '[data-tour="refresh-button"]',
    placement: 'bottom',
    nextButtonText: 'Notifications',
  },
  {
    id: 'notifications',
    title: 'Order Notifications & Alerts 🔔',
    content: 'This floating button shows the number of pending orders that need your attention. Click it to see important notifications and alerts about orders that require immediate action.',
    target: '[data-tour="notification-fab"]',
    placement: 'left',
    nextButtonText: 'Order Workflow',
  },
  {
    id: 'order-workflow',
    title: 'Understanding Order Flow 📋',
    content: 'Orders flow through these stages: Pending (new orders) → Confirmed (accepted) → Preparing (kitchen working) → Ready (finished cooking) → Served (delivered to customer). Your job is to keep this flow moving smoothly!',
    target: '[data-tour="active-orders-table"]',
    placement: 'top',
    nextButtonText: 'Time Management',
  },
  {
    id: 'time-tracking',
    title: 'Order Timing & Efficiency ⏰',
    content: 'Pay attention to order times and estimated ready times. This helps you prioritize orders and ensure customers don\'t wait too long. Older orders should generally be handled first.',
    target: '[data-tour="order-time-column"]',
    placement: 'top',
    nextButtonText: 'Kitchen Coordination',
  },
  {
    id: 'kitchen-coordination',
    title: 'Kitchen Communication 👨‍🍳',
    content: 'When you mark an order as "Preparing", the kitchen knows to start cooking. When they\'re done, mark it as "Ready" so servers know to pick it up. Good communication keeps everything flowing!',
    target: '[data-tour="order-status-chips"]',
    placement: 'top',
    nextButtonText: 'Customer Service',
  },
  {
    id: 'customer-service',
    title: 'Customer Experience Focus 😊',
    content: 'Remember, each order represents a customer waiting for their meal. Quick and accurate order processing leads to happy customers and better reviews. You\'re a key part of the customer experience!',
    target: '[data-tour="active-orders-table"]',
    placement: 'center',
    nextButtonText: 'Mobile Usage',
  },
  {
    id: 'mobile-friendly',
    title: 'Mobile-Friendly Design 📱',
    content: 'This dashboard works great on tablets and phones too! You can manage orders from anywhere in the restaurant, making it easy to stay on top of operations while moving around.',
    target: '[data-tour="dashboard-header"]',
    placement: 'bottom',
    nextButtonText: 'Ready to Go!',
  },
  {
    id: 'completion',
    title: 'You\'re Ready to Rock! 🎉',
    content: 'Perfect! You now know how to use your operator dashboard effectively. Remember: confirm orders quickly, keep the kitchen informed, and focus on smooth order flow. You\'ve got this!',
    target: '[data-tour="dashboard-header"]',
    placement: 'center',
    nextButtonText: 'Start Operating',
    showSkip: false,
  },
];

export default operatorTourSteps;