import { TourStep } from '../../../contexts/TourContext';

export const superAdminTourSteps: TourStep[] = [
  {
    id: 'welcome',
    title: 'Welcome, Super Admin! 👑',
    content: 'Welcome to Dino\'s Super Admin Dashboard! You have the highest level of access and control over the entire platform. Let\'s explore the powerful features at your disposal for managing multiple venues and users.',
    target: '[data-tour="dashboard-header"]',
    placement: 'bottom',
    nextButtonText: 'Show Me Everything',
    showSkip: true,
  },
  {
    id: 'comprehensive-stats',
    title: 'Platform-Wide Analytics 📊',
    content: 'As a Super Admin, you can see comprehensive statistics across all venues in your workspace. Monitor total orders, revenue, table utilization, and menu performance across your entire restaurant network.',
    target: '[data-tour="stats-cards"]',
    placement: 'bottom',
    nextButtonText: 'Revenue Insights',
  },
  {
    id: 'revenue-analytics',
    title: 'Advanced Revenue Analytics 💰',
    content: 'This advanced chart shows revenue trends with the ability to compare different venues, time periods, and performance metrics. Use this data to identify top-performing locations and growth opportunities.',
    target: '[data-tour="revenue-chart"]',
    placement: 'top',
    nextButtonText: 'Order Management',
  },
  {
    id: 'order-oversight',
    title: 'Cross-Venue Order Management 📦',
    content: 'Monitor orders across all venues in real-time. You can see order status distribution, identify bottlenecks, and ensure consistent service quality across your restaurant network.',
    target: '[data-tour="order-status-chart"]',
    placement: 'left',
    nextButtonText: 'Multi-Venue Tables',
  },
  {
    id: 'table-management',
    title: 'Multi-Venue Table Operations 🏪',
    content: 'Get a bird\'s-eye view of table occupancy across all your venues. This helps you understand capacity utilization and identify opportunities for optimization or expansion.',
    target: '[data-tour="table-status-chart"]',
    placement: 'right',
    nextButtonText: 'Order Monitoring',
  },
  {
    id: 'order-monitoring',
    title: 'Real-Time Order Monitoring 👀',
    content: 'Monitor recent orders across all venues. You can drill down into specific locations, track performance metrics, and ensure operational standards are maintained everywhere.',
    target: '[data-tour="recent-orders"]',
    placement: 'top',
    nextButtonText: 'Admin Tools',
  },
  {
    id: 'admin-tools',
    title: 'Super Admin Quick Tools ⚡',
    content: 'Access powerful administrative tools for managing orders, menus, tables, and users across all venues. These tools give you the ability to make system-wide changes efficiently.',
    target: '[data-tour="quick-actions"]',
    placement: 'top',
    nextButtonText: 'User Management',
  },
  {
    id: 'user-management',
    title: 'Platform User Management 👥',
    content: 'Manage all users across the platform - create admin accounts, assign venue access, manage roles and permissions. You control who has access to what across your entire network.',
    target: '[data-tour="users-nav"]',
    placement: 'right',
    nextButtonText: 'Venue Management',
  },
  {
    id: 'venue-management',
    title: 'Multi-Venue Administration 🏢',
    content: 'Add new venues, configure settings, manage subscriptions, and oversee operations across your restaurant network. You can set up new locations and manage existing ones from here.',
    target: '[data-tour="venues-nav"]',
    placement: 'right',
    nextButtonText: 'Workspace Control',
  },
  {
    id: 'workspace-management',
    title: 'Workspace Configuration 🌐',
    content: 'Manage workspace-wide settings, billing, subscriptions, and global configurations. This is where you control the overall platform settings that affect all venues.',
    target: '[data-tour="workspace-nav"]',
    placement: 'right',
    nextButtonText: 'Role Management',
  },
  {
    id: 'role-permissions',
    title: 'Advanced Role & Permission System 🔐',
    content: 'Create custom roles, define granular permissions, and manage access control across the platform. You can create specialized roles for different types of users and venues.',
    target: '[data-tour="roles-nav"]',
    placement: 'right',
    nextButtonText: 'System Analytics',
  },
  {
    id: 'system-analytics',
    title: 'Platform-Wide Analytics 📈',
    content: 'Access comprehensive analytics covering all venues: revenue trends, user activity, system performance, and business intelligence. Make data-driven decisions for your entire network.',
    target: '[data-tour="analytics-nav"]',
    placement: 'right',
    nextButtonText: 'System Settings',
  },
  {
    id: 'system-settings',
    title: 'Global System Configuration ⚙️',
    content: 'Configure platform-wide settings, integrations, payment gateways, and system preferences. These settings affect all venues and users in your workspace.',
    target: '[data-tour="settings-nav"]',
    placement: 'right',
    nextButtonText: 'Monitoring Tools',
  },
  {
    id: 'monitoring-tools',
    title: 'System Health & Monitoring 🔍',
    content: 'Monitor system health, user activity, performance metrics, and security across the platform. Keep track of how your entire network is performing and identify issues early.',
    target: '[data-tour="monitoring-nav"]',
    placement: 'right',
    nextButtonText: 'Support Features',
  },
  {
    id: 'support-features',
    title: 'User Support & Help Desk 🆘',
    content: 'Access support tools to help users across all venues. You can view support tickets, provide assistance, and ensure all users are getting the help they need.',
    target: '[data-tour="support-nav"]',
    placement: 'right',
    nextButtonText: 'Scaling Operations',
  },
  {
    id: 'scaling-operations',
    title: 'Scaling Your Restaurant Network 🚀',
    content: 'Use the insights and tools you\'ve learned about to scale your operations efficiently. Monitor performance, optimize processes, and expand your restaurant network with confidence.',
    target: '[data-tour="dashboard-header"]',
    placement: 'center',
    nextButtonText: 'Master Control',
  },
  {
    id: 'completion',
    title: 'Master of Your Domain! 🎯',
    content: 'Excellent! You now have complete knowledge of the Super Admin capabilities. You can manage multiple venues, oversee all operations, and scale your restaurant business effectively. The platform is yours to command!',
    target: '[data-tour="dashboard-header"]',
    placement: 'center',
    nextButtonText: 'Take Control',
    showSkip: false,
  },
];

export default superAdminTourSteps;